import {
  createRootRoute,
  HeadContent,
  Outlet,
  Scripts,
} from "@tanstack/react-router";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState, type ReactNode } from "react";
import { AuthProvider } from "@/lib/auth/provider";
import { I18nProvider } from "@/lib/i18n/i18n";
import { AutoDemoProvider } from "@/components/auto-demo";
import { PreviewHostBridge } from "@/components/preview-host-bridge";
import appCss from "../styles.css?url";

const APP_NAME = "漢字でんしゃ";

// A plain `rel="stylesheet"` link here is render-blocking: the browser holds
// first paint on every route (including /login) until this third-party
// fetch resolves. Confirmed via a real Playwright/Chromium run (mobile
// device emulation, JS enabled) against a local deploy-equivalent build --
// this was the one real failure caught (`net::ERR_CONNECTION_RESET`) behind
// a report of the page "stalling halfway through loading" on mobile, with
// zero JS console errors otherwise.
//
// Fixed via the standard loadCSS preload+swap recipe, done as a raw inline
// script in RootDocument's <head> below rather than a `links` entry: React's
// server renderer silently drops ANY prop matching /^on/i (confirmed by
// inspecting the actual SSR output -- a first attempt using a plain `onload`
// string in the `links` array below rendered with no `onload` attribute at
// all), so there is no way to get a literal `onload="..."` HTML attribute
// out of TanStack Router's link-object API. The inline script instead
// creates the `<link>` node itself via the DOM API with a real bound
// function, which never goes through React's prop filtering, runs
// synchronously as the browser's own HTML parser reaches it, and doesn't
// depend on hydration completing at all.
const GOOGLE_FONTS_HREF =
  "https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;700&family=Noto+Sans+TC:wght@400;500;700&family=Shippori+Mincho:wght@500;600;700&family=Zen+Kaku+Gothic+New:wght@400;500;700&display=swap";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1, viewport-fit=cover" },
      { title: APP_NAME },
      {
        name: "description",
        content: "文部科学省1026字を、列車に乗せて学ぶ。保護者のための小学漢字学習。",
      },
      { name: "theme-color", content: "#F4EFE4" },
      // iOS ignores the manifest entirely for home-screen installs: the
      // title comes from here (and truncates on the home screen, hence the
      // short one), and the icon from the apple-touch-icon link below.
      { name: "apple-mobile-web-app-title", content: "でんしゃ" },
      { name: "apple-mobile-web-app-capable", content: "yes" },
      { name: "apple-mobile-web-app-status-bar-style", content: "default" },
    ],
    links: [
      { rel: "icon", type: "image/svg+xml", href: "/favicon.svg" },
      { rel: "stylesheet", href: appCss },
      // Both of these used to point into /__grok/, the preview host's own
      // asset directory -- and the manifest there does not exist at all, so
      // every page load has been 404ing on it. These are the app's own now
      // (public/, generated by scripts/gen-pwa-icons.mjs).
      { rel: "manifest", href: "/manifest.webmanifest" },
      { rel: "apple-touch-icon", sizes: "180x180", href: "/icon-180.png" },
      { rel: "preconnect", href: "https://fonts.googleapis.com" },
      { rel: "preconnect", href: "https://fonts.gstatic.com", crossOrigin: "anonymous" },
    ],
  }),
  component: RootDocument,
});

function Providers({ children }: { children: ReactNode }) {
  const [queryClient] = useState(
    () =>
      new QueryClient({
        defaultOptions: { queries: { staleTime: 15_000, retry: 1 } },
      }),
  );
  return <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>;
}

function RootDocument() {
  return (
    <html lang="ja" className="antialiased" suppressHydrationWarning>
      <head>
        <HeadContent />
        {/* Loads the Google Fonts stylesheet without blocking first paint --
            see the GOOGLE_FONTS_HREF comment above for why this has to be a
            raw script rather than a `links` entry. Synchronous + no `defer`/
            `async`/`type="module"` so it runs immediately as the parser
            reaches it, before the (large) hydration bundle. */}
        <script
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: `(function(){var l=document.createElement("link");l.rel="preload";l.as="style";l.href=${JSON.stringify(GOOGLE_FONTS_HREF)};l.onload=function(){l.onload=null;l.rel="stylesheet";};document.head.appendChild(l);})();`,
          }}
        />
        {/* JS-disabled fallback for the script above -- without this, a
            visitor with JS off would never get the webfont at all. */}
        <noscript>
          <link rel="stylesheet" href={GOOGLE_FONTS_HREF} />
        </noscript>
      </head>
      <body className="font-sans">
        <PreviewHostBridge />
        <AuthProvider>
          <I18nProvider>
            <Providers>
              <AutoDemoProvider>
                <Outlet />
              </AutoDemoProvider>
            </Providers>
          </I18nProvider>
        </AuthProvider>
        <Scripts />
      </body>
    </html>
  );
}
