import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
// @ts-expect-error -- plain .mjs build tool, no type declarations by design
import { encodeQrMatrix } from "./qr-encode.mjs";
import {
  PASS_QR_HREF,
  PASS_QR_MATRIX,
  TICKET_QR_HREF,
  TICKET_QR_MATRIX,
} from "../src/lib/ticket-qr.ts";

/**
 * The matrices in src/lib/ticket-qr.ts are baked constants, so nothing at
 * runtime would notice if one encoded the wrong URL -- a wrong QR still
 * scans, it just goes somewhere else. These tests re-encode each href and
 * require the baked rows to match exactly.
 */

test("the encoder reproduces the long-standing TICKET_QR_MATRIX byte-for-byte", () => {
  // This matrix predates scripts/qr-encode.mjs and was generated by a
  // different tool, so matching it is an independent check of the encoder
  // itself -- not a tautology. It is what makes the PASS_QR_MATRIX
  // assertion below trustworthy.
  assert.deepEqual(encodeQrMatrix(TICKET_QR_HREF), [...TICKET_QR_MATRIX]);
});

test("PASS_QR_MATRIX really encodes PASS_QR_HREF", () => {
  assert.deepEqual(encodeQrMatrix(PASS_QR_HREF), [...PASS_QR_MATRIX]);
});

test("the pass QR points at the app origin and carries no credential", () => {
  assert.equal(PASS_QR_HREF, "https://app.kanji-ai.jp/");
  assert.equal(PASS_QR_HREF.includes("?"), false);
  assert.equal(PASS_QR_HREF.includes("#"), false);
  assert.equal(/token|magic|session|key=|sig=/i.test(PASS_QR_HREF), false);
});

test("both matrices are square, 25x25, and binary", () => {
  for (const matrix of [TICKET_QR_MATRIX, PASS_QR_MATRIX]) {
    assert.equal(matrix.length, 25);
    for (const row of matrix) {
      assert.equal(row.length, 25);
      assert.match(row, /^[01]+$/);
    }
  }
});

test("the two matrices differ -- the pass is not silently reusing the stub's URL", () => {
  assert.notDeepEqual([...PASS_QR_MATRIX], [...TICKET_QR_MATRIX]);
});

test("the encoder refuses rather than guessing when input exceeds what it implements", () => {
  assert.throws(() => encodeQrMatrix("x".repeat(100)), /version above 3/);
});

test("no identity field can reach the QR module -- it is constants and drawing only", () => {
  const src = readFileSync("src/lib/ticket-qr.ts", "utf8");
  assert.equal(/childId|userId|nickname|childName|\bemail\b/.test(src), false);
  // The encoder is a build tool; importing it at runtime would mean a matrix
  // computed from whatever the caller passed. (Naming it in a comment is
  // fine, and is how a reader finds out where the constants came from.)
  assert.equal(/^\s*import[^\n]*qr-encode/m.test(src), false);
});
