/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiHealthDbRouteImport } from './routes/api/health-db'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppCatalogRouteImport } from './routes/app/catalog'
import { Route as AppMapRouteImport } from './routes/app/map'
import { Route as AppMistakesRouteImport } from './routes/app/mistakes'
import { Route as AppStampsRouteImport } from './routes/app/stamps'
import { Route as AppWorkshopRouteImport } from './routes/app/workshop'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoCatalogRouteImport } from './routes/demo/catalog'
import { Route as DemoMapRouteImport } from './routes/demo/map'
import { Route as DemoMistakesRouteImport } from './routes/demo/mistakes'
import { Route as DemoParentRouteImport } from './routes/demo/parent'
import { Route as DemoStampsRouteImport } from './routes/demo/stamps'
import { Route as DemoWorkshopRouteImport } from './routes/demo/workshop'
import { Route as SubscribeSuccessRouteImport } from './routes/subscribe.success'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksShopifyRouteImport } from './routes/api/webhooks/shopify'
import { Route as AppChildChildIdRouteImport } from './routes/app/child.$childId'
import { Route as AppKanjiCharRouteImport } from './routes/app/kanji.$char'
import { Route as AppParentIndexRouteImport } from './routes/app/parent.index'
import { Route as AppParentSettingsRouteImport } from './routes/app/parent.settings'
import { Route as DemoKanjiCharRouteImport } from './routes/demo/kanji.$char'
import { Route as AppChildChildIdIndexRouteImport } from './routes/app/child.$childId.index'
import { Route as AppChildChildIdCatalogRouteImport } from './routes/app/child.$childId.catalog'
import { Route as AppChildChildIdMapRouteImport } from './routes/app/child.$childId.map'
import { Route as AppChildChildIdMistakesRouteImport } from './routes/app/child.$childId.mistakes'
import { Route as AppChildChildIdStampsRouteImport } from './routes/app/child.$childId.stamps'
import { Route as AppChildChildIdWorkshopRouteImport } from './routes/app/child.$childId.workshop'
import { Route as AppParentReportChildIdRouteImport } from './routes/app/parent.report.$childId'
import { Route as AppChildChildIdKanjiCharRouteImport } from './routes/app/child.$childId.kanji.$char'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthDbRoute = ApiHealthDbRouteImport.update({
  id: '/api/health-db',
  path: '/api/health-db',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMistakesRoute = AppMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStampsRoute = AppStampsRouteImport.update({
  id: '/stamps',
  path: '/stamps',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkshopRoute = AppWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => AppRouteRoute,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCatalogRoute = DemoCatalogRouteImport.update({
  id: '/demo/catalog',
  path: '/demo/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMapRoute = DemoMapRouteImport.update({
  id: '/demo/map',
  path: '/demo/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMistakesRoute = DemoMistakesRouteImport.update({
  id: '/demo/mistakes',
  path: '/demo/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoParentRoute = DemoParentRouteImport.update({
  id: '/demo/parent',
  path: '/demo/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStampsRoute = DemoStampsRouteImport.update({
  id: '/demo/stamps',
  path: '/demo/stamps',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWorkshopRoute = DemoWorkshopRouteImport.update({
  id: '/demo/workshop',
  path: '/demo/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeSuccessRoute = SubscribeSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SubscribeRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksShopifyRoute = ApiWebhooksShopifyRouteImport.update({
  id: '/api/webhooks/shopify',
  path: '/api/webhooks/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChildChildIdRoute = AppChildChildIdRouteImport.update({
  id: '/child/$childId',
  path: '/child/$childId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKanjiCharRoute = AppKanjiCharRouteImport.update({
  id: '/kanji/$char',
  path: '/kanji/$char',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppParentIndexRoute = AppParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppParentSettingsRoute = AppParentSettingsRouteImport.update({
  id: '/parent/settings',
  path: '/parent/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const DemoKanjiCharRoute = DemoKanjiCharRouteImport.update({
  id: '/demo/kanji/$char',
  path: '/demo/kanji/$char',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChildChildIdIndexRoute = AppChildChildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChildChildIdRoute,
} as any)
const AppChildChildIdCatalogRoute = AppChildChildIdCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppChildChildIdRoute,
} as any)
const AppChildChildIdMapRoute = AppChildChildIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppChildChildIdRoute,
} as any)
const AppChildChildIdMistakesRoute = AppChildChildIdMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AppChildChildIdRoute,
} as any)
const AppChildChildIdStampsRoute = AppChildChildIdStampsRouteImport.update({
  id: '/stamps',
  path: '/stamps',
  getParentRoute: () => AppChildChildIdRoute,
} as any)
const AppChildChildIdWorkshopRoute = AppChildChildIdWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => AppChildChildIdRoute,
} as any)
const AppParentReportChildIdRoute = AppParentReportChildIdRouteImport.update({
  id: '/parent/report/$childId',
  path: '/parent/report/$childId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChildChildIdKanjiCharRoute =
  AppChildChildIdKanjiCharRouteImport.update({
    id: '/kanji/$char',
    path: '/kanji/$char',
    getParentRoute: () => AppChildChildIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/handoff': typeof HandoffRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/parents': typeof ParentsRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/health-db': typeof ApiHealthDbRoute
  '/app/admin': typeof AppAdminRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/map': typeof AppMapRoute
  '/app/mistakes': typeof AppMistakesRoute
  '/app/stamps': typeof AppStampsRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/demo/catalog': typeof DemoCatalogRoute
  '/demo/map': typeof DemoMapRoute
  '/demo/mistakes': typeof DemoMistakesRoute
  '/demo/parent': typeof DemoParentRoute
  '/demo/stamps': typeof DemoStampsRoute
  '/demo/workshop': typeof DemoWorkshopRoute
  '/subscribe/success': typeof SubscribeSuccessRoute
  '/app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/shopify': typeof ApiWebhooksShopifyRoute
  '/app/child/$childId': typeof AppChildChildIdRouteWithChildren
  '/app/kanji/$char': typeof AppKanjiCharRoute
  '/app/parent/settings': typeof AppParentSettingsRoute
  '/demo/kanji/$char': typeof DemoKanjiCharRoute
  '/app/parent/': typeof AppParentIndexRoute
  '/app/child/$childId/catalog': typeof AppChildChildIdCatalogRoute
  '/app/child/$childId/map': typeof AppChildChildIdMapRoute
  '/app/child/$childId/mistakes': typeof AppChildChildIdMistakesRoute
  '/app/child/$childId/stamps': typeof AppChildChildIdStampsRoute
  '/app/child/$childId/workshop': typeof AppChildChildIdWorkshopRoute
  '/app/parent/report/$childId': typeof AppParentReportChildIdRoute
  '/app/child/$childId/': typeof AppChildChildIdIndexRoute
  '/app/child/$childId/kanji/$char': typeof AppChildChildIdKanjiCharRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/handoff': typeof HandoffRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/parents': typeof ParentsRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/health-db': typeof ApiHealthDbRoute
  '/app/admin': typeof AppAdminRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/map': typeof AppMapRoute
  '/app/mistakes': typeof AppMistakesRoute
  '/app/stamps': typeof AppStampsRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/demo/catalog': typeof DemoCatalogRoute
  '/demo/map': typeof DemoMapRoute
  '/demo/mistakes': typeof DemoMistakesRoute
  '/demo/parent': typeof DemoParentRoute
  '/demo/stamps': typeof DemoStampsRoute
  '/demo/workshop': typeof DemoWorkshopRoute
  '/subscribe/success': typeof SubscribeSuccessRoute
  '/app': typeof AppIndexRoute
  '/demo': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/shopify': typeof ApiWebhooksShopifyRoute
  '/app/kanji/$char': typeof AppKanjiCharRoute
  '/app/parent/settings': typeof AppParentSettingsRoute
  '/demo/kanji/$char': typeof DemoKanjiCharRoute
  '/app/parent': typeof AppParentIndexRoute
  '/app/child/$childId/catalog': typeof AppChildChildIdCatalogRoute
  '/app/child/$childId/map': typeof AppChildChildIdMapRoute
  '/app/child/$childId/mistakes': typeof AppChildChildIdMistakesRoute
  '/app/child/$childId/stamps': typeof AppChildChildIdStampsRoute
  '/app/child/$childId/workshop': typeof AppChildChildIdWorkshopRoute
  '/app/parent/report/$childId': typeof AppParentReportChildIdRoute
  '/app/child/$childId': typeof AppChildChildIdIndexRoute
  '/app/child/$childId/kanji/$char': typeof AppChildChildIdKanjiCharRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/handoff': typeof HandoffRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/parents': typeof ParentsRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/health-db': typeof ApiHealthDbRoute
  '/app/admin': typeof AppAdminRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/map': typeof AppMapRoute
  '/app/mistakes': typeof AppMistakesRoute
  '/app/stamps': typeof AppStampsRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/demo/catalog': typeof DemoCatalogRoute
  '/demo/map': typeof DemoMapRoute
  '/demo/mistakes': typeof DemoMistakesRoute
  '/demo/parent': typeof DemoParentRoute
  '/demo/stamps': typeof DemoStampsRoute
  '/demo/workshop': typeof DemoWorkshopRoute
  '/subscribe/success': typeof SubscribeSuccessRoute
  '/app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/shopify': typeof ApiWebhooksShopifyRoute
  '/app/child/$childId': typeof AppChildChildIdRouteWithChildren
  '/app/kanji/$char': typeof AppKanjiCharRoute
  '/app/parent/settings': typeof AppParentSettingsRoute
  '/demo/kanji/$char': typeof DemoKanjiCharRoute
  '/app/parent/': typeof AppParentIndexRoute
  '/app/child/$childId/catalog': typeof AppChildChildIdCatalogRoute
  '/app/child/$childId/map': typeof AppChildChildIdMapRoute
  '/app/child/$childId/mistakes': typeof AppChildChildIdMistakesRoute
  '/app/child/$childId/stamps': typeof AppChildChildIdStampsRoute
  '/app/child/$childId/workshop': typeof AppChildChildIdWorkshopRoute
  '/app/parent/report/$childId': typeof AppParentReportChildIdRoute
  '/app/child/$childId/': typeof AppChildChildIdIndexRoute
  '/app/child/$childId/kanji/$char': typeof AppChildChildIdKanjiCharRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/handoff'
    | '/login'
    | '/onboard'
    | '/parents'
    | '/subscribe'
    | '/admin/login'
    | '/api/health-db'
    | '/app/admin'
    | '/app/catalog'
    | '/app/map'
    | '/app/mistakes'
    | '/app/stamps'
    | '/app/workshop'
    | '/demo/catalog'
    | '/demo/map'
    | '/demo/mistakes'
    | '/demo/parent'
    | '/demo/stamps'
    | '/demo/workshop'
    | '/subscribe/success'
    | '/app/'
    | '/demo/'
    | '/api/auth/$'
    | '/api/webhooks/shopify'
    | '/app/child/$childId'
    | '/app/kanji/$char'
    | '/app/parent/settings'
    | '/demo/kanji/$char'
    | '/app/parent/'
    | '/app/child/$childId/catalog'
    | '/app/child/$childId/map'
    | '/app/child/$childId/mistakes'
    | '/app/child/$childId/stamps'
    | '/app/child/$childId/workshop'
    | '/app/parent/report/$childId'
    | '/app/child/$childId/'
    | '/app/child/$childId/kanji/$char'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/handoff'
    | '/login'
    | '/onboard'
    | '/parents'
    | '/subscribe'
    | '/admin/login'
    | '/api/health-db'
    | '/app/admin'
    | '/app/catalog'
    | '/app/map'
    | '/app/mistakes'
    | '/app/stamps'
    | '/app/workshop'
    | '/demo/catalog'
    | '/demo/map'
    | '/demo/mistakes'
    | '/demo/parent'
    | '/demo/stamps'
    | '/demo/workshop'
    | '/subscribe/success'
    | '/app'
    | '/demo'
    | '/api/auth/$'
    | '/api/webhooks/shopify'
    | '/app/kanji/$char'
    | '/app/parent/settings'
    | '/demo/kanji/$char'
    | '/app/parent'
    | '/app/child/$childId/catalog'
    | '/app/child/$childId/map'
    | '/app/child/$childId/mistakes'
    | '/app/child/$childId/stamps'
    | '/app/child/$childId/workshop'
    | '/app/parent/report/$childId'
    | '/app/child/$childId'
    | '/app/child/$childId/kanji/$char'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/handoff'
    | '/login'
    | '/onboard'
    | '/parents'
    | '/subscribe'
    | '/admin/login'
    | '/api/health-db'
    | '/app/admin'
    | '/app/catalog'
    | '/app/map'
    | '/app/mistakes'
    | '/app/stamps'
    | '/app/workshop'
    | '/demo/catalog'
    | '/demo/map'
    | '/demo/mistakes'
    | '/demo/parent'
    | '/demo/stamps'
    | '/demo/workshop'
    | '/subscribe/success'
    | '/app/'
    | '/demo/'
    | '/api/auth/$'
    | '/api/webhooks/shopify'
    | '/app/child/$childId'
    | '/app/kanji/$char'
    | '/app/parent/settings'
    | '/demo/kanji/$char'
    | '/app/parent/'
    | '/app/child/$childId/catalog'
    | '/app/child/$childId/map'
    | '/app/child/$childId/mistakes'
    | '/app/child/$childId/stamps'
    | '/app/child/$childId/workshop'
    | '/app/parent/report/$childId'
    | '/app/child/$childId/'
    | '/app/child/$childId/kanji/$char'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  HandoffRoute: typeof HandoffRoute
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  ParentsRoute: typeof ParentsRoute
  SubscribeRoute: typeof SubscribeRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiHealthDbRoute: typeof ApiHealthDbRoute
  DemoCatalogRoute: typeof DemoCatalogRoute
  DemoMapRoute: typeof DemoMapRoute
  DemoMistakesRoute: typeof DemoMistakesRoute
  DemoParentRoute: typeof DemoParentRoute
  DemoStampsRoute: typeof DemoStampsRoute
  DemoWorkshopRoute: typeof DemoWorkshopRoute
  DemoIndexRoute: typeof DemoIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksShopifyRoute: typeof ApiWebhooksShopifyRoute
  DemoKanjiCharRoute: typeof DemoKanjiCharRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health-db': {
      id: '/api/health-db'
      path: '/api/health-db'
      fullPath: '/api/health-db'
      preLoaderRoute: typeof ApiHealthDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mistakes': {
      id: '/app/mistakes'
      path: '/mistakes'
      fullPath: '/app/mistakes'
      preLoaderRoute: typeof AppMistakesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/stamps': {
      id: '/app/stamps'
      path: '/stamps'
      fullPath: '/app/stamps'
      preLoaderRoute: typeof AppStampsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workshop': {
      id: '/app/workshop'
      path: '/workshop'
      fullPath: '/app/workshop'
      preLoaderRoute: typeof AppWorkshopRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/catalog': {
      id: '/demo/catalog'
      path: '/demo/catalog'
      fullPath: '/demo/catalog'
      preLoaderRoute: typeof DemoCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/map': {
      id: '/demo/map'
      path: '/demo/map'
      fullPath: '/demo/map'
      preLoaderRoute: typeof DemoMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mistakes': {
      id: '/demo/mistakes'
      path: '/demo/mistakes'
      fullPath: '/demo/mistakes'
      preLoaderRoute: typeof DemoMistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/parent': {
      id: '/demo/parent'
      path: '/demo/parent'
      fullPath: '/demo/parent'
      preLoaderRoute: typeof DemoParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/stamps': {
      id: '/demo/stamps'
      path: '/demo/stamps'
      fullPath: '/demo/stamps'
      preLoaderRoute: typeof DemoStampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/workshop': {
      id: '/demo/workshop'
      path: '/demo/workshop'
      fullPath: '/demo/workshop'
      preLoaderRoute: typeof DemoWorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/success': {
      id: '/subscribe/success'
      path: '/success'
      fullPath: '/subscribe/success'
      preLoaderRoute: typeof SubscribeSuccessRouteImport
      parentRoute: typeof SubscribeRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/shopify': {
      id: '/api/webhooks/shopify'
      path: '/api/webhooks/shopify'
      fullPath: '/api/webhooks/shopify'
      preLoaderRoute: typeof ApiWebhooksShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/child/$childId': {
      id: '/app/child/$childId'
      path: '/child/$childId'
      fullPath: '/app/child/$childId'
      preLoaderRoute: typeof AppChildChildIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/kanji/$char': {
      id: '/app/kanji/$char'
      path: '/kanji/$char'
      fullPath: '/app/kanji/$char'
      preLoaderRoute: typeof AppKanjiCharRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/parent/': {
      id: '/app/parent/'
      path: '/parent'
      fullPath: '/app/parent/'
      preLoaderRoute: typeof AppParentIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/parent/settings': {
      id: '/app/parent/settings'
      path: '/parent/settings'
      fullPath: '/app/parent/settings'
      preLoaderRoute: typeof AppParentSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/demo/kanji/$char': {
      id: '/demo/kanji/$char'
      path: '/demo/kanji/$char'
      fullPath: '/demo/kanji/$char'
      preLoaderRoute: typeof DemoKanjiCharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/child/$childId/': {
      id: '/app/child/$childId/'
      path: '/'
      fullPath: '/app/child/$childId/'
      preLoaderRoute: typeof AppChildChildIdIndexRouteImport
      parentRoute: typeof AppChildChildIdRoute
    }
    '/app/child/$childId/catalog': {
      id: '/app/child/$childId/catalog'
      path: '/catalog'
      fullPath: '/app/child/$childId/catalog'
      preLoaderRoute: typeof AppChildChildIdCatalogRouteImport
      parentRoute: typeof AppChildChildIdRoute
    }
    '/app/child/$childId/map': {
      id: '/app/child/$childId/map'
      path: '/map'
      fullPath: '/app/child/$childId/map'
      preLoaderRoute: typeof AppChildChildIdMapRouteImport
      parentRoute: typeof AppChildChildIdRoute
    }
    '/app/child/$childId/mistakes': {
      id: '/app/child/$childId/mistakes'
      path: '/mistakes'
      fullPath: '/app/child/$childId/mistakes'
      preLoaderRoute: typeof AppChildChildIdMistakesRouteImport
      parentRoute: typeof AppChildChildIdRoute
    }
    '/app/child/$childId/stamps': {
      id: '/app/child/$childId/stamps'
      path: '/stamps'
      fullPath: '/app/child/$childId/stamps'
      preLoaderRoute: typeof AppChildChildIdStampsRouteImport
      parentRoute: typeof AppChildChildIdRoute
    }
    '/app/child/$childId/workshop': {
      id: '/app/child/$childId/workshop'
      path: '/workshop'
      fullPath: '/app/child/$childId/workshop'
      preLoaderRoute: typeof AppChildChildIdWorkshopRouteImport
      parentRoute: typeof AppChildChildIdRoute
    }
    '/app/parent/report/$childId': {
      id: '/app/parent/report/$childId'
      path: '/parent/report/$childId'
      fullPath: '/app/parent/report/$childId'
      preLoaderRoute: typeof AppParentReportChildIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/child/$childId/kanji/$char': {
      id: '/app/child/$childId/kanji/$char'
      path: '/kanji/$char'
      fullPath: '/app/child/$childId/kanji/$char'
      preLoaderRoute: typeof AppChildChildIdKanjiCharRouteImport
      parentRoute: typeof AppChildChildIdRoute
    }
  }
}

interface AppChildChildIdRouteChildren {
  AppChildChildIdCatalogRoute: typeof AppChildChildIdCatalogRoute
  AppChildChildIdMapRoute: typeof AppChildChildIdMapRoute
  AppChildChildIdMistakesRoute: typeof AppChildChildIdMistakesRoute
  AppChildChildIdStampsRoute: typeof AppChildChildIdStampsRoute
  AppChildChildIdWorkshopRoute: typeof AppChildChildIdWorkshopRoute
  AppChildChildIdIndexRoute: typeof AppChildChildIdIndexRoute
  AppChildChildIdKanjiCharRoute: typeof AppChildChildIdKanjiCharRoute
}

const AppChildChildIdRouteChildren: AppChildChildIdRouteChildren = {
  AppChildChildIdCatalogRoute: AppChildChildIdCatalogRoute,
  AppChildChildIdMapRoute: AppChildChildIdMapRoute,
  AppChildChildIdMistakesRoute: AppChildChildIdMistakesRoute,
  AppChildChildIdStampsRoute: AppChildChildIdStampsRoute,
  AppChildChildIdWorkshopRoute: AppChildChildIdWorkshopRoute,
  AppChildChildIdIndexRoute: AppChildChildIdIndexRoute,
  AppChildChildIdKanjiCharRoute: AppChildChildIdKanjiCharRoute,
}

const AppChildChildIdRouteWithChildren = AppChildChildIdRoute._addFileChildren(
  AppChildChildIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppMapRoute: typeof AppMapRoute
  AppMistakesRoute: typeof AppMistakesRoute
  AppStampsRoute: typeof AppStampsRoute
  AppWorkshopRoute: typeof AppWorkshopRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChildChildIdRoute: typeof AppChildChildIdRouteWithChildren
  AppKanjiCharRoute: typeof AppKanjiCharRoute
  AppParentSettingsRoute: typeof AppParentSettingsRoute
  AppParentIndexRoute: typeof AppParentIndexRoute
  AppParentReportChildIdRoute: typeof AppParentReportChildIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppMapRoute: AppMapRoute,
  AppMistakesRoute: AppMistakesRoute,
  AppStampsRoute: AppStampsRoute,
  AppWorkshopRoute: AppWorkshopRoute,
  AppIndexRoute: AppIndexRoute,
  AppChildChildIdRoute: AppChildChildIdRouteWithChildren,
  AppKanjiCharRoute: AppKanjiCharRoute,
  AppParentSettingsRoute: AppParentSettingsRoute,
  AppParentIndexRoute: AppParentIndexRoute,
  AppParentReportChildIdRoute: AppParentReportChildIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface SubscribeRouteChildren {
  SubscribeSuccessRoute: typeof SubscribeSuccessRoute
}

const SubscribeRouteChildren: SubscribeRouteChildren = {
  SubscribeSuccessRoute: SubscribeSuccessRoute,
}

const SubscribeRouteWithChildren = SubscribeRoute._addFileChildren(
  SubscribeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  HandoffRoute: HandoffRoute,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  ParentsRoute: ParentsRoute,
  SubscribeRoute: SubscribeRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiHealthDbRoute: ApiHealthDbRoute,
  DemoCatalogRoute: DemoCatalogRoute,
  DemoMapRoute: DemoMapRoute,
  DemoMistakesRoute: DemoMistakesRoute,
  DemoParentRoute: DemoParentRoute,
  DemoStampsRoute: DemoStampsRoute,
  DemoWorkshopRoute: DemoWorkshopRoute,
  DemoIndexRoute: DemoIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksShopifyRoute: ApiWebhooksShopifyRoute,
  DemoKanjiCharRoute: DemoKanjiCharRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
